set(UNIC_THREAD_MODEL os2)
set(UNIC_IPC_MODEL os2)
set(UNIC_TIME_PROFILER_MODEL os2)
set(UNIC_DIR_MODEL os2)
set(UNIC_RWLOCK_MODEL general)
set(UNIC_LIBRARYLOADER_MODEL os2)

set(UNIC_PLATFORM_LINK_LIBRARIES os2386)

set(UNIC_PLATFORM_DEFINES
  -D_REENTRANT
  )
