set(UNIC_THREAD_MODEL solaris)
set(UNIC_IPC_MODEL sysv)
set(UNIC_TIME_PROFILER_MODEL solaris)
set(UNIC_DIR_MODEL posix)
set(UNIC_LIBRARYLOADER_MODEL posix)

set(UNIC_PLATFORM_LINK_LIBRARIES socket nsl rt)

set(UNIC_PLATFORM_DEFINES
  -D_REENTRANT
  -D_POSIX_PTHREAD_SEMANTICS
  )
