set(UNIC_THREAD_MODEL atheos)
set(UNIC_IPC_MODEL none)
set(UNIC_TIME_PROFILER_MODEL posix)
set(UNIC_DIR_MODEL posix)
set(UNIC_RWLOCK_MODEL general)
set(UNIC_LIBRARYLOADER_MODEL posix)

set(UNIC_PLATFORM_LINK_LIBRARIES rt dl)

set(UNIC_PLATFORM_DEFINES
  -D_REENTRANT
  )
