set(UNIC_THREAD_MODEL posix)
set(UNIC_IPC_MODEL sysv)
set(UNIC_TIME_PROFILER_MODEL posix)
set(UNIC_DIR_MODEL posix)
set(UNIC_LIBRARYLOADER_MODEL posix)

set(UNIC_PLATFORM_LDFLAGS -L/usr/lib/threads)
set(UNIC_PLATFORM_LINK_LIBRARIES c_r -pthread)

set(UNIC_PLATFORM_DEFINES
  -D_REENTRANT
  -D_THREAD_SAFE
  )
