set(UNIC_THREAD_MODEL win)
set(UNIC_IPC_MODEL win)
set(UNIC_TIME_PROFILER_MODEL win)
set(UNIC_DIR_MODEL win)
set(UNIC_LIBRARYLOADER_MODEL win)

if (NOT CMAKE_SIZEOF_VOID_P)
  set(CMAKE_SIZEOF_VOID_P 4)
endif ()

set(UNIC_PLATFORM_LINK_LIBRARIES ws2_32)
