set(UNIC_THREAD_MODEL posix)
set(UNIC_IPC_MODEL posix)
set(UNIC_TIME_PROFILER_MODEL posix)
set(UNIC_DIR_MODEL posix)
set(UNIC_LIBRARYLOADER_MODEL posix)

set(UNIC_PLATFORM_LINK_LIBRARIES -pthread rt)

set(UNIC_PLATFORM_DEFINES
  -D_REENTRANT
  -D_XOPEN_SOURCE_EXTENDED=1
  -D_POSIX_PII_SOCKET
  -D_OSF_SOURCE
  -D_XOPEN_SOURCE=500
  -D_POSIX_SOURCE=199506L
  )
